name: PR Vulnerability Scan

# Required permissions to upload scan results to GitHub Security tab
permissions:
  contents: read
  security-events: write

on:
  pull_request:
    types: [opened, reopened]  # Run scan when PR is opened or reopened
    branches: [main]
  workflow_dispatch:  

jobs:
  # Scan the source code files in the repo
  fs-scan:
    name: Scan Source Code (File System)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trivy - File System Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-fs-results.sarif
          severity: CRITICAL

      - name: Upload Scan Results to Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs-results.sarif

  # Scan vulnerabilities in the Docker image
  image-scan:
    name: Scan Docker Image
    needs: fs-scan  # Runs after FS scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . -t pr-check-image

      - name: Trivy - Docker Image Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: pr-check-image
          scan-type: image
          ignore-unfixed: true
          format: sarif
          output: trivy-image-results.sarif
          severity: CRITICAL

      - name: Upload Scan Results to Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image-results.sarif
